name = "AMO"
uuid = "84f1a4cc-bedd-412d-9d4a-321e40b84e6a"
version = "0.1.0"
authors = ["Yichao Yu <yyc1992@gmail.com>"]

[deps]
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
julia = "1.11"
SpecialFunctions = "2.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
